>### Module
>Consider a module to be the same as a code library. A file containing a set of functions you want to include in your application.

>### Create a Module
>To create a module just save the code you want in a file with the file extension .py

>### Using a module
>we can use the module we just created, by using the import statement

In [1]:
# import a module that i've create
import basic_math

In [2]:
basic_math?

Type:        module
String form: <module 'basic_math' from 'C:\\Users\\DIMAS\\latihanpy\\python_material\\basic_math.py'>
File:        c:\users\dimas\latihanpy\python_material\basic_math.py
Docstring:   This is an example of docstring to demonstrate a module.

In [3]:
# using the module
val_add = basic_math.add(5,5)
val_div = basic_math.divide(5,5)
val_sub = basic_math.subtract(5,5)

In [4]:
# print result
print(val_add)
print(val_div)
print(val_sub)

10
1.0
0


>### Built-in Module
>a built-in module refers to a module that is part of the standard library and comes pre-installed with Python. These modules provide a wide range of functionalities and can be used without the need for additional installations.
>
>For example, modules like math, random, and os are built-in modules. 

>### Math Module
>These functions cannot be used with complex numbers; use the functions of the same name from the cmath module if you require support for complex numbers. The distinction between functions which support complex numbers and those which don’t is made since most users do not want to learn quite as much mathematics as required to understand complex numbers.
>
>These are the math [module](https://docs.python.org/3/library/math.html?highlight=math%20module#module-math)

In [5]:
# import module
import math

In [6]:
math?

Type:        module
String form: <module 'math' (built-in)>
Docstring:  
This module provides access to the mathematical functions
defined by the C standard.

In [7]:
# calculate the square root of number
sqrt_val = math.sqrt(25)

# calculate the factorial number
factorial_val = math.factorial(5)

# calculate the sosine of an angle
cos_val = math.cos(math.radians(45))

# calculate the power
pow_val = math.pow(5,2)

In [8]:
# print result
print(sqrt_val)
print(factorial_val)
print(cos_val)
print(pow_val)

5.0
120
0.7071067811865476
25.0


>### Random Module
>This module implements pseudo-random number generators for various distributions.
For integers, there is uniform selection from a range. For sequences, there is uniform selection of a random element, a function to generate a random permutation of a list in-place, and a function for random sampling without replacement.
>
>These are the random [module](https://docs.python.org/3/library/math.html?highlight=math%20module#module-math)

In [9]:
# import module
import random

In [10]:
# using random.radint()
print(random.randint(10,15))

13


In [11]:
# using random.choice()
fruits = ['apple', 'banana', 'cherry', 'orange', 'watermelon']
print(random.choice(fruits))

watermelon


In [12]:
# using random.sample()
print(random.sample(fruits,3))

['watermelon', 'cherry', 'banana']


>### Datetime Module
>The datetime module supplies classes for manipulating dates and times.
While date and time arithmetic is supported, the focus of the implementation is on efficient attribute extraction for output formatting and manipulation.
>
>These are the datetime [module](https://docs.python.org/3/library/datetime.html?highlight=datetime%20module#module-datetime)

In [13]:
import datetime

In [14]:
# get the current date and time
current_datetime = datetime.datetime.now()

# get the current date
current_date = datetime.date.today()

# create a spesific date
spesific_date = datetime.date(2023, 9 , 20)

# calculate the diffrence between two dates
date_diff = spesific_date - current_date

In [15]:
print(current_datetime)
print(current_date)
print(spesific_date)
print(date_diff)

2023-10-06 08:10:33.648291
2023-10-06
2023-09-20
-16 days, 0:00:00


>### Numpy
>This reference manual details functions, modules, and objects included in NumPy, describing what they are and what they do. For learning how to use NumPy, see the complete documentation.

In [16]:
# import liblary
import numpy as np

In [17]:
# creating an array from a python list
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [18]:
# range of values
range_arr = np.arange(0,10,2) # start,stop,step
print(range_arr)

[0 2 4 6 8]


In [19]:
# other example
a = np.array([1,2,3])
b = np.array([4,5,6])

In [20]:
# arithmatic operation
print(a + b)
print(a * b)
print(a / b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


>### Pandas
>pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.

In [21]:
import pandas as pd

In [22]:
# example of series (one dim array)
vals = [1,2,3]
idxs = ['a','b','c']

In [24]:
# call series module with
s = pd.Series(vals,idxs)
print(s)

a    1
b    2
c    3
dtype: int64


In [25]:
# opening and reading text data (csv)
df = pd.read_csv('https://data.jakarta.go.id/dataset/14ab98731e79939ecaa26ee4222531d2/resource/9f1c2bb6164087f0f0c62b3451e24dd9/download/Data-Penumpang-Bus-Transjakarta-Desember-2021.csv')

In [26]:
df

tahun  bulan                    jenis kode_trayek  \
0     2021     12               Mikrotrans      JAK.88   
1     2021     12               Mikrotrans      JAK.85   
2     2021     12               Mikrotrans      JAK.84   
3     2021     12               Mikrotrans      JAK.80   
4     2021     12               Mikrotrans      JAK.77   
..     ...    ...                      ...         ...   
117   2021     12  Angkutan Umum Integrasi          1A   
118   2021     12  Angkutan Umum Integrasi         12B   
119   2021     12  Angkutan Umum Integrasi         11Q   
120   2021     12  Angkutan Umum Integrasi         11D   
121   2021     12  Angkutan Umum Integrasi         10K   

                                   trayek  jumlah_penumpang  
0    Terminal Tanjung Priok - Ancol Barat             43967  
1                Bintara - Cipinang Indah             40103  
2    Terminal Kampung Melayu - Kapin Raya             59193  
3               Rawa Buaya - Rawa Kompeni             70475  
4           Tanjung Priok - Jembatan Item             77697  
..                                    ...               ...  
117                      PIK - Balai Kota                 0  
118                         Pluit - Senen                 0  
119  Kampung Melayu - Pulo Gebang via BKT                 0  
120   Pulo Gebang - Pulo Gadung 2 via PIK                 0  
121  Tanjung Priok - Senen via Taman  BMW                 0  

[122 rows x 6 columns]

In [28]:
df[(df["jumlah_penumpang"] > 0) & (df["jenis"] == "Angkutan Umum Integrasi")]

tahun  bulan                    jenis kode_trayek               trayek  \
99    2021     12  Angkutan Umum Integrasi          6H  Senen - Lebak Bulus   
107   2021     12  Angkutan Umum Integrasi          1R  Senen - Tanah Abang   

     jumlah_penumpang  
99                  8  
107               176

In [33]:
df[(df["jumlah_penumpang"] == 0)]

tahun  bulan                    jenis kode_trayek  \
85    2021     12  Angkutan Umum Integrasi          9H   
86    2021     12  Angkutan Umum Integrasi          9E   
87    2021     12  Angkutan Umum Integrasi          9D   
88    2021     12  Angkutan Umum Integrasi          8K   
89    2021     12  Angkutan Umum Integrasi          8E   
90    2021     12  Angkutan Umum Integrasi          8D   
91    2021     12  Angkutan Umum Integrasi          8C   
92    2021     12  Angkutan Umum Integrasi          7P   
93    2021     12  Angkutan Umum Integrasi          7D   
94    2021     12  Angkutan Umum Integrasi          7B   
95    2021     12  Angkutan Umum Integrasi          7A   
96    2021     12  Angkutan Umum Integrasi          6R   
97    2021     12  Angkutan Umum Integrasi          6N   
98    2021     12  Angkutan Umum Integrasi          6M   
100   2021     12  Angkutan Umum Integrasi          6C   
101   2021     12  Angkutan Umum Integrasi          5M   
102   2021     12  Angkutan Umum Integrasi          5F   
103   2021     12  Angkutan Umum Integrasi          5B   
104   2021     12  Angkutan Umum Integrasi          4F   
105   2021     12  Angkutan Umum Integrasi          4B   
106   2021     12  Angkutan Umum Integrasi          3E   
108   2021     12  Angkutan Umum Integrasi          1Q   
109   2021     12  Angkutan Umum Integrasi          1P   
110   2021     12  Angkutan Umum Integrasi          1N   
111   2021     12  Angkutan Umum Integrasi          1M   
112   2021     12  Angkutan Umum Integrasi          1H   
113   2021     12  Angkutan Umum Integrasi          1F   
114   2021     12  Angkutan Umum Integrasi          1E   
115   2021     12  Angkutan Umum Integrasi          1C   
116   2021     12  Angkutan Umum Integrasi          1B   
117   2021     12  Angkutan Umum Integrasi          1A   
118   2021     12  Angkutan Umum Integrasi         12B   
119   2021     12  Angkutan Umum Integrasi         11Q   
120   2021     12  Angkutan Umum Integrasi         11D   
121   2021     12  Angkutan Umum Integrasi         10K   

                                      trayek  jumlah_penumpang  
85                          Cipedak - Blok M                 0  
86                 Kebayoran Lama - Jelambar                 0  
87                Pasar Minggu - Tanah Abang                 0  
88                     Batu Sari-Tanah Abang                 0  
89                          Bintaro - Blok M                 0  
90                            Joglo - Blok M                 0  
91              Kebayoran Lama - Tanah Abang                 0  
92                       Pondok Kelapa - BKN                 0  
93                           Pancoran - TMII                 0  
94                 Kampung Rambutan - Blok M                 0  
95            Kampung Rambutan - Lebak Bulus                 0  
96            Ragunan - Stasin MRT Fatmawati                 0  
97               Ragunan - Blok M via Kemang                 0  
98               Stasiun Manggarai - Blok  M                 0  
100  Stasin Tebet - Karet via Patra Kuningan                 0  
101  Kampung Melayu - Tanah Abang via Cikini                 0  
102             Kampung Melayu - Tanah Abang                 0  
103              Stasiun Tebet - Bidara Cina                 0  
104               Pinang Ranti - Pulo Gadung                 0  
105                   Stasiun Manggarai - UI                 0  
106   Sentraland Cengkareng - Puri Kembangan                 0  
108                          Rempoa - Blok M                 0  
109                 Senen - Bundaran Senayan                 0  
110                     Tanah Abang - Blok M                 0  
111                          Meruya - Blok M                 0  
112         Tanah Abang - Stasiun Gondangdia                 0  
113      Stasiun Palmerah - Bundaran Senayan                 0  
114                    Pondok  Labu - Blok M                 0  
115                    Pesanggr

### REFERENCE
1. https://www.w3schools.com/python/python_modules.asp
2. https://docs.python.org/3/library/index.html
3. https://numpy.org/doc/stable/reference/index.html
4. https://pandas.pydata.org/docs/index.html
5. https://data.jakarta.go.id/dataset/data-penumpang-bus-transjakarta-januari-2021/resource/9f1c2bb6164087f0f0c62b3451e24dd9